apiVersion: v1
kind: PersistentVolume
metadata:
  name: gram-pv
spec:
  capacity:
    storage: 512Mi
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.gram.pvHostPath }}