#ENC[AES256_GCM,data:1i4Y48s4oBfiOA3P3/uUL+YybWFO/TT2/tXuH2nNipqloPLIxBcybczM311LmxZftbLmaxkKzPAiTzPlw5HM,iv:vgYfpyvigRd6OnMYzlMWbgs9X9PmVl84B1GCtJ0uzHQ=,tag:UdbG0RXvNentcJbcZ3zfIA==,type:comment]
#ENC[AES256_GCM,data:D5P+qNxHDZ5mU+0MNtNhiJk7eif0zoQk/Nst+bMww3Mh86AzWyboGOc=,iv:IGGjvo8gEYjWFM8oLmM9GP0dVHW+b6+tT1HrnWQf+dU=,tag:bHagk3cqG4VmLFz2+S8UoA==,type:comment]
#ENC[AES256_GCM,data:mzFwQYstU8SXB5467wvlczF/YvMw5l2ax/nsRHmhIBVQ8P4LQaW7vultMjtS5kyvqPLcOqWGPHCWq79TYfaA1T+pOlnRnDD+DyF11XxVpZo=,iv:uPmTy0wOPjZ+9x5Pc4AEqt9CRLd0G/+Na1CTxzLDxjs=,tag:adtTXV9wZnAsgBv4NwamyA==,type:comment]
#ENC[AES256_GCM,data:qDjUdT0AZSTvWlEUZnVQzXbqSECOThUcND88Z4OMjET+z4HpvzYHht8N8WU3VTruReUGBQbf6kDlYwWN/sZLWeRhBRx6jCDdciOUjw==,iv:WXPHQGJC4iuLkdwQnnkmncrS/4QwZENv8xgG5hUqSrE=,tag:CReg0k1zV7pZzQvJyVs4Mg==,type:comment]
#ENC[AES256_GCM,data:uZXJGlchDIn63z8c2HuqtfOn7eQEFdZpSg8QVS9KuPOQn4Aqn9Gvw5kdEyf+gu310FHfGNzXaozr4aOS/0YP6Pd3S0iunP6EOxs=,iv:RJdIf/dQ1Uw/Wh0t6Z/YYUl4y0Mf7oiEMEJtyMkyLAk=,tag:kgdguiAoBph7MAZOF71vTg==,type:comment]
#ENC[AES256_GCM,data:J4+z29x+BdR0ziqDA92jJxm3aTHsEY20l8I=,iv:snb+GiAF7JJzN/AIJ1P+Dx9u6BEm/Cz9pABTLrsoaTU=,tag:1U4G0ozaAjftniBnCo2cWw==,type:comment]
apiVersion: ENC[AES256_GCM,data:3/g=,iv:EalAx5p1Sfr1swtNFNehQjHbLVfFj7/W4JrWWvXcX0o=,tag:afwk47BstHHPLjCmI5quQg==,type:str]
kind: ENC[AES256_GCM,data:K+4hiLRT,iv:j2TQPEeG8F+Ps+9pDvRlML5IwW36Ny64UM7EmCB6H4E=,tag:Vx+7enQdhvrxkCCNOEy7mQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EbAJaMm61ocJ/KFMz2WdMercTg==,iv:yA92kM2zHode0pXbbGQbD2kFuLhnYrFSuMfsoypEhIA=,tag:TAipWw6Ijqsn3ncNnp26NQ==,type:str]
    namespace: ENC[AES256_GCM,data:GndB2GI=,iv:hqsMtK4tEM46tsxR0ZW7Oa7h/ZgyG7kh3BgeMppiLNA=,tag:6O8CfouEiFnudOlAD1VBvA==,type:str]
type: ENC[AES256_GCM,data:cfXM2elI,iv:HmBZmdpP8+BGvGG2iZUCuYBBCElnnUvaCa96RcGZ39A=,tag:WT8D6Olv3aFbShhWsrexcQ==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:diXP1CiN19m/biMLUa9OxjIs5zQ=,iv:e+HtXLSmE0Oj60gBwWFzHp1kKwKrenjh6Q1wLw7PVTY=,tag:KpDIpDX4XZbdbVi5xRAEAw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:35BTpQNXJ1p2AS9RWaQtCum3bmHWB6jSiFTpizDQLoEw4vVnA4JgAQ==,iv:oe6hveJysvYdA15KZgYa/WnN7xoKKDouIUY/Jus3P6M=,tag:miQmbt4TrMuuT66KXnbisg==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:oBUgxoPEDGgypyEzUQz1hVYMyTg3hRqOdTv/DyEB1HJ3fgiSWWrdHbKynkA9FYZu66HrS1fkC9/PZWGn7p8c7Q==,iv:J/Fhvc5+Q6J4bqUcyFHUCTfjNmrorJFPt4KYb0yUgF0=,tag:kScJJyxXTC/GK23vz4xu4A==,type:str]
    KOPIA_BUCKET: ENC[AES256_GCM,data:yD4UxAPC9lftPA2NGVxPTPkkIIer19vpMeDOlnixT6nleZpsLnRTsHer0o8O,iv:YaGWkMtKctDa/36XXG9M2bkIue3wLVnGwYZqRUHGCEg=,tag:qOlh8/ah5rADpdbUR48uKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHJoTEtuUSBBNW52Y0s4
            M0R2RWd2eExPMDhSM08rbmMzYkRCVnRvL1owMUpub2pFZWkyQwpjaThmVGljMWR5
            WTVTUkhKUUt3eG9LUHZDZGxLSmowYVJwc0Q5K2RzZnFrCi0tLSBHU2t3YythcU92
            RnhLYWIyNnN4cjErMHZ0UjZtMkJGbzQyZ01WTUVhRjN3ChpttNdlYMx+dyx8SLME
            mCQ+J+LhgPdKr1kvtnEfRaVUdkVQ7gNTwWREX8WpO16B65r1t2jW7VEQg420kSvX
            3uQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qw8fz5uzfj5eayrrffqdztejc5yzjvhqahpx56lglktf0lm3g8qusuup9g8
    lastmodified: "2026-08-05T12:47:05Z"
    mac: ENC[AES256_GCM,data:dwunY5eZtzc53JsWvJQ8J8nwtU/P3WdHctPcv4FBN+lXqkV357qI47LEPW1W/c+kJKwuHo3Z/O61tPDBe6qmiXYn+WxGFzjWIuNyWX5Y0wogeSzLQqzSHios7rzHhqZqHlU687xJuKqwqoimm8xuAXvBXclZgfbm0VKgXSzvFbc=,iv:PeJYpoGtUFhyGvMP7/0ANX9tp0UYR0TEB2wyPlg/XFw=,tag:15CnMLrzDybXh9C1zn1HXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
