#ENC[AES256_GCM,data:FtI7LgYGBrHMunapVmPohSu+oXimmeehp6XxEaa5s9ZzOqkpAOXbqU/2jXy4SPgknTIDHZQm54cDLzDghFweGTWQ/1Y6F2jQ0ug=,iv:Ao+So0RRH0lqYVoS890VrvN3tBb1mZjjxkSWiBE2iY0=,tag:fHaOMIB1aTxSxNUeE1Hrzg==,type:comment]
#ENC[AES256_GCM,data:fWn9R3lxtSPZBE3bRCAmcgF1XvepC9HIuoLpVZLge+U9wbofdODdh0X2OazHjG9mwxGz8Smy+nfTZfUjMHGsNmgEVO7hCMMGdddsVRfOCw==,iv:hxtwGlz4B9tmXkRGS0qcespQNhwk9v6N2+nIcTTEaUk=,tag:j9p0/a4MIDdgQfkqnQo4VQ==,type:comment]
#ENC[AES256_GCM,data:KV5/VC3J88nQfB31hrumH5aEQ1IE6qwfniTRYCmN2NxUij42iB/+O+5QY+mvqxiToghQg1XdsgTDGL2A7qVawzBTxgpfR5qw6fRiUg==,iv:rxoth8GLc3lndUymuC9TX9mfvMOdTPmujd2ZCVo7+ro=,tag:+BY3MqzRktJTfEb2u5yP/Q==,type:comment]
#ENC[AES256_GCM,data:WOWx+ANrIags4f4FNtoY6Pb0wMblgQgQzuFII/4nnfQyXzj9C9hVFkPHDKUWQwGpQXRbm+j0fCHIr9x+vvg=,iv:WUA+AL7ZMIv3MCHUA86S9N6wjcYkSbUKSgteifSJ5ck=,tag:F8wKfm8QXrL626U0NiouEQ==,type:comment]
#
#ENC[AES256_GCM,data:BN5TXTNO94I1zRDgMI0wEEhlKqCh99Vgtn9vvqewVNlXyO8HFJv3gFZ4BjiwqVaPY2og8kJkPnYwYDAiPAElxcQ7aAFy5/0XFc7I3w==,iv:FA9FHzjewYL2JmpZzJZgqmcre4yFm0f8tE5DRW1QTsk=,tag:kmv6PJzBD57jHypX9RPn+g==,type:comment]
#ENC[AES256_GCM,data:zqn+3p8VlhXilmukD5/6a2Qfw2jQVdY=,iv:5zxvhv3p3AzrN0iTo1qvLujK324V+uXhYTJksPrwz3g=,tag:V7f2nghO+RBsajY+Rc13vA==,type:comment]
#ENC[AES256_GCM,data:H4yPsoEKx9hhNjFrfjMHpjy79B2Ppr/eLYcACiHlPNF5R0+BOt06cZi1IoBOh5mWTTk=,iv:Cp1lBjUlBRTskPh+y5cq1wpJZRz37XMWnK+NeaMFP2k=,tag:WbRTcDcUSY537XSy66goug==,type:comment]
apiVersion: ENC[AES256_GCM,data:UGg=,iv:VLL78edttfIoxapsUjQMI04/xXzpVA9GDw3Ad3LDEfk=,tag:uUiGUFbtprnUzN2gPigsoA==,type:str]
kind: ENC[AES256_GCM,data:us0yKPQh,iv:dvcoPWL2KE7RHhsyCwXQgThqF6zOQdFScFui8zZlGQY=,tag:xXIWnA4lYjBZVYGfFZu0QQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3YDq8gONcJ3Esof1eyzR5iwMgkvuYP8=,iv:sLlRe8sTpIz6gSig1PApqi8BmFWlxqUd0vnanw1n/E4=,tag:rbwu53GJ+mQ9Mty3qAovew==,type:str]
    namespace: ENC[AES256_GCM,data:AcCfDGLgkkHb,iv:gc4W/x27cK8W1epPHNdF3A6yRyPAe3/4VgUupyebbko=,tag:8yb0F4h35RmpHcpw97UPxA==,type:str]
type: ENC[AES256_GCM,data:r8mS4123,iv:Nrh9TTsuNbj7L5oTNE+V1aAon6kSMWQI1VNXSvaICvw=,tag:4opPg0pjhs6q6EqNBV1tqw==,type:str]
stringData:
    magicdns-suffix: ENC[AES256_GCM,data:PLU2j47OXksnH9KryxPIb/e5Tm0=,iv:K6+rg/HgQZdg3U+3IVFVzW+NAZyYVuVoeM7ngbva3ic=,tag:ArRoCjl90HtnraEtifLmrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHJoTEtuUSBBNG1lVzFK
            ak5EN1ptOUViR3ZGWmlWQXBJSm8wL3JwNE54a0lKdGVUUmxMSAovcUd2Nkh5MzV6
            QTV1MWhaZHJYRDdXQUMvZHNkWFppVTBFb2tIVWR5RElNCi0tLSBDMFFMSTlybHdq
            RjBtQ0ZVcVdKQ2EwUjcyNkZBeVJKNHhqbzAxZTJzbHVRCgtaEf2dN/wuVrkn+F7/
            lR0Wj2iEsaYyWpQXeQD2C5XJgJ+Nx7X2kSYZ8E2uaNSrVLpCtBZjCBzpLFXhjM7e
            UgE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qw8fz5uzfj5eayrrffqdztejc5yzjvhqahpx56lglktf0lm3g8qusuup9g8
    lastmodified: "2026-07-29T17:03:08Z"
    mac: ENC[AES256_GCM,data:Wd1ZxZRRLNi4F826C69h4i+AFp7vogn9CnxTlfGns+cg9CWsaxS81BbVRGEHinYnq8vaXHtznAL0O+UHzbu+fMnuEPCAbMY3VM7upi6CPD4X4XioHCap3us4BdUrS7HFxsaX3EXVzDG6oRqnASq31BwhvDLfbx9sa9t0B03wp4k=,iv:sFo2ZkmM2NAXDxl58VgWZhrSpJ7L6nzn2kVOod9J7t4=,tag:GtxFT88fnCf0xvndogh8lA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
