version: 1
metadata:
  name: My - Passwordless flow
entries:
- attrs:
    authentication: none
    denied_action: message_continue
    designation: authentication
    layout: stacked
    name: Passwordless-flow
    policy_engine_mode: any
    title: Passwordless Flow
  identifiers:
    slug: passwordless-flow
  model: authentik_flows.flow
  id: flow
- attrs:
    user_fields:
    - username
  identifiers:
    name: Passwordless Indentification
  id: my-authentication-identification
  model: authentik_stages_identification.identificationstage
- identifiers:
    order: 10
    stage: !KeyOf my-authentication-identification
    target: !KeyOf flow
  model: authentik_flows.flowstagebinding
- attrs:
    device_classes:
    - webauthn
    last_auth_threshold: seconds=0
    not_configured_action: deny
    webauthn_user_verification: required
  identifiers:
    name: Passwordless WebAuthn
  id: my-passwordless-webauthn
  model: authentik_stages_authenticator_validate.authenticatorvalidatestage
- identifiers:
    order: 20
    stage: !KeyOf my-passwordless-webauthn
    target: !KeyOf flow
  model: authentik_flows.flowstagebinding
- identifiers:
    name: Passwordless User Login
  id: my-authentication-login
  model: authentik_stages_user_login.userloginstage
- identifiers:
    order: 30
    stage: !KeyOf my-authentication-login
    target: !KeyOf flow
  model: authentik_flows.flowstagebinding
