apiVersion: v1
kind: Service
metadata:
  name: samba
  labels:
    app: samba
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  selector:
    app: samba
  ports:
    - name: smb
      port: {{ .Values.service.port }}
      targetPort: smb
      protocol: TCP
