apiVersion: v2
name: gha-runner-scale-set-wrapper
description: Wrapper chart for gha-runner-scale-set to provide resources to work with custom CA
version: 0.1.0

dependencies:
  - name: gha-runner-scale-set
    version: 0.14.2
    repository: oci://ghcr.io/actions/actions-runner-controller-charts