apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole

spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.pihole.cname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pihole
            port:
              number: 80