apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
data:
{{- range $path, $_ := .Files.Glob "blueprints/*.yaml" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
