apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gram
spec:
  destination:
    namespace: gram
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - gitops-values.yaml
    path: charts/gram
    repoURL: https://github.com/roman-ks/home-projects-parent-k8s.git
    targetRevision: gha
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true