apiVersion: apps/v1
kind: Deployment
metadata:
  name: gram-voice
  labels:
    app: gram-voice
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: gram-voice
  template:
    metadata:
      labels:
        app: gram-voice
        app.kubernetes.io/name: gram-voice
    spec:
      containers:
      - name: gram-voice
        image: "{{ .Values.gramVoice.image.repository }}:{{ .Values.gramVoice.image.tag }}"
        env:
        - name: SERVER_START_TIMEOUT
          value: 10m
        - name: INPUT
          value: /input
        - name: SERVER_BINARY_PATH
          value: "/app/whisper-server"
        volumeMounts:
        - name: gram-storage
          mountPath: /models
          subPath: models
        - name: gram-storage
          mountPath: /input
          subPath: input
      volumes:
      - name: gram-storage
        persistentVolumeClaim:
          claimName: gram-voice-pvc
---
