apiVersion: v1
kind: Secret
metadata:
  name: memos-oidc-secret
  namespace: authentik
data:
  client-id: {{ .Values.memos.oidc.clientId | b64enc }}
  client-secret: {{ .Values.memos.oidc.clientSecret | b64enc }}
